language: php
php:
- 5.6
install:
- composer install
env:
  global:
  - APP_ENV=testing
  - APP_KEY=1uiGjPxjIcfGuHE7rjimjkiwfJh2XQhh
  - TWILIO_ACCOUNT_SID=anaccountsid
  - TWILIO_AUTH_TOKEN=fnwjnfi349h3ifu
  - TWILIO_NUMBER=+1555984574